### ISSUE TITLE
Settings saving and kisses

### ISSUE THREAD

**Issue by BenjaminGTACoder** [ikt32/GTAVMenuBase#3]
I love your base. Thanks for making it, do you mind if I use it in my trampoline physics mod when it releases? It'll be released to gta5-mods.

Also, I was playing about with the menu and noticed there wasn't a save function yet, I'd love to contribute and create one but I simply despise file management and it'd be a terrible mess if I did haha. I don't suppose you could make the save settings function some time soon? I've been playing about with this base a lot and love it to bits.

Thanks,
Benjamin

**Comment by Le-Fix** [comment]
I don't know E66666666 aka ikt opinion on that, but the majority of my mods have more settings saved/loaded then represented in the menu therefore I like the fact that saving/loading is not part of the mod menu directly even though the include simpleini code provides bunch of functions to handle that easily, you might check his manual transmission source or (somewhat smaller) my quadcopter mod and look at the settings files

**Comment by ikt32** [comment]
Thanks for the comment! 

Hmmm, I chose to keep the menu settings isolated from the rest of the mod's settings. Since I don't have options in the menu that allow changing its own properties (position, size, etc) I didn't feel the need to implement saving menu settings yet, but if you want to change stuff on-the-fly, that's okay too. 

If you just want to manage your own settings you could (should) make your own settings file management. It isn't too difficult even if just using the Windows API, but I prefer SimpleINI to have it worry about types and such for me :)
As @Le-Fix said, you can check out implementations of settings in other mods using the same library:

* Quadcopter: [header](https://github.com/Le-Fix/gta5-quadcopter/blob/master/LeFixDrone/Settings.h) and [implementation](https://github.com/Le-Fix/gta5-quadcopter/blob/master/LeFixDrone/Settings.cpp)
* Manual Transmission: [header](https://github.com/E66666666/GTAVManualTransmission/blob/master/Gears/ScriptSettings.hpp) and [implementation](https://github.com/E66666666/GTAVManualTransmission/blob/master/Gears/ScriptSettings.cpp)

Some choices were made to defer setting the settings file locations after the application has started, but you can also just hardcode them instead of looking up relative directories.

**Comment by BenjaminGTACoder** [comment]
Thank you so much for the response, that's perfect.
