### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by ghost** [ikt32/GTAVMenuBase#7]
I see missing credits.. ;) (well unnamed credits anyways)

**Comment by ikt32** [comment]
Is [this](https://www.unknowncheats.me/forum/grand-theft-auto-v/200692-originbase-sudomod-1-37-a.html) you? I got the source from [here](https://forums.gta5-mods.com/topic/8541/c-simple-menu-base-library) so tracing back original authors was a bit hard. Sorry I missed you :)

I can't download it since I don't have an account there (or I can't find my login...), but it looks like your code yes. Do you have a preference of how credits are handled? Readme, separate credits file, or inside the main source files?

**Comment by ghost** [comment]
Just a name anywhere 😛 and thanks 😄

**Comment by ghost** [comment]
Oh and yeah it is me 😃 (well the creator, not the guy who posted those files)
